apiVersion: v1
kind: Service
metadata:
  name: darwin-custom-collector-service
  namespace: monitoring-logging
spec:
  selector:
    app: darwin-custom-collector
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000